pipeline {
    agent any

    stages {
        stage('Selenium Grid Setup') {
            steps {
                echo 'Hello Selenium'
            }
        }
        stage('Selenoid Setup') {
            steps {
                echo 'Hello Selenoid'
            }
        }
    }
}
